import type { Profile } from "@prisma/client";

interface props {
  profile: Profile;
  className?: string;
  onClick?: (...args: any) => any;
}

// This component uses the Profile type generated by Prisma because it's only being passed the profile data from the user documents.
export function UserCircle({ profile, className, onClick }: props) {
  return (
    <div
      className={`${className} cursor-pointer bg-gray-400 rounded-full flex justify-center items-center`}
      onClick={onClick}
    >
      <h2>
        {profile.firstName.charAt(0).toUpperCase()}
        {profile.lastName.charAt(0).toUpperCase()}
      </h2>
    </div>
  );
}
